name: Code Quality Checks

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Type check
      run: bun x tsc --noEmit

    - name: Lint check (if eslint is configured)
      run: |
        if [ -f "eslint.config.js" ] || [ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ]; then
          bun x eslint src/ --ext .ts,.js
        else
          echo "ESLint not configured, skipping lint check"
        fi
      continue-on-error: true

    - name: Build check
      run: bun run build
