name: Build Docker Image

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun ci

    - name: Build app
      run: bun run build --target bun

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine version
      id: gitversion
      run: |
        VERSION_JSON=$(dotnet-gitversion /config GitVersion.yml /output json)
        SEMVER=$(echo "$VERSION_JSON" | jq -r '.SemVer')
        FULLSEMVER=$(echo "$VERSION_JSON" | jq -r '.FullSemVer')
        echo "semver=$SEMVER" >> "$GITHUB_OUTPUT"
        echo "fullsemver=$FULLSEMVER" >> "$GITHUB_OUTPUT"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.semver }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          VERSION=${{ steps.gitversion.outputs.fullsemver }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd "${{ secrets.DEPLOY_WORKDIR }}"
          IMAGE="ghcr.io/stdray/animemov-bot:${{ steps.gitversion.outputs.semver }}"
          CONTAINER_NAME="animemov-bot"
          PASSWORD="${{ secrets.DEPLOY_PASSWORD }}"
          run_sudo() {
            printf '%s\n' "$PASSWORD" | sudo -S -p '' "$@"
          }
          run_sudo docker pull "$IMAGE"
          run_sudo docker stop "$CONTAINER_NAME" || true
          run_sudo docker rm "$CONTAINER_NAME" || true
          run_sudo docker run -d --name "$CONTAINER_NAME" --restart unless-stopped --env-file .env "$IMAGE"
          run_sudo docker system prune -a -f
